//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ApplicationData", "Audiometer_Pacient1", "Pacient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Pacient), "Audiometer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Audiometer), true)]
[assembly: EdmRelationshipAttribute("ApplicationData", "Audiogram_Audiometer1", "Audiometer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ApplicationData.Implementation.Audiometer), "Audiogram", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ApplicationData.Implementation.Audiogram), true)]

#endregion

namespace ApplicationData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ApplicationDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ApplicationDataObjectContext object using the connection string found in the 'ApplicationDataObjectContext' section of the application configuration file.
        /// </summary>
        public ApplicationDataObjectContext() : base("name=ApplicationDataObjectContext", "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(string connectionString) : base(connectionString, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ApplicationDataObjectContext object.
        /// </summary>
        public ApplicationDataObjectContext(EntityConnection connection) : base(connection, "ApplicationDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Pacient> Pacients
        {
            get
            {
                if ((_Pacients == null))
                {
                    _Pacients = base.CreateObjectSet<Pacient>("Pacients");
                }
                return _Pacients;
            }
        }
        private ObjectSet<Pacient> _Pacients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Audiometer> Audiometers
        {
            get
            {
                if ((_Audiometers == null))
                {
                    _Audiometers = base.CreateObjectSet<Audiometer>("Audiometers");
                }
                return _Audiometers;
            }
        }
        private ObjectSet<Audiometer> _Audiometers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Audiogram> Audiograms
        {
            get
            {
                if ((_Audiograms == null))
                {
                    _Audiograms = base.CreateObjectSet<Audiogram>("Audiograms");
                }
                return _Audiograms;
            }
        }
        private ObjectSet<Audiogram> _Audiograms;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Pacients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPacients(Pacient pacient)
        {
            base.AddObject("Pacients", pacient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Audiometers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAudiometers(Audiometer audiometer)
        {
            base.AddObject("Audiometers", audiometer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Audiograms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAudiograms(Audiogram audiogram)
        {
            base.AddObject("Audiograms", audiogram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Audiogram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Audiogram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Audiogram object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="ear">Initial value of the Ear property.</param>
        /// <param name="frequency">Initial value of the Frequency property.</param>
        /// <param name="intensity">Initial value of the Intensity property.</param>
        /// <param name="reponse">Initial value of the reponse property.</param>
        /// <param name="audiogram_Audiometer">Initial value of the audiogram_Audiometer property.</param>
        public static Audiogram CreateAudiogram(global::System.Int32 id, global::System.String ear, global::System.Int32 frequency, global::System.Int32 intensity, global::System.String reponse, global::System.Int32 audiogram_Audiometer)
        {
            Audiogram audiogram = new Audiogram();
            audiogram.Id = id;
            audiogram.Ear = ear;
            audiogram.Frequency = frequency;
            audiogram.Intensity = intensity;
            audiogram.reponse = reponse;
            audiogram.audiogram_Audiometer = audiogram_Audiometer;
            return audiogram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ear
        {
            get
            {
                return _Ear;
            }
            set
            {
                OnEarChanging(value);
                ReportPropertyChanging("Ear");
                _Ear = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ear");
                OnEarChanged();
            }
        }
        private global::System.String _Ear;
        partial void OnEarChanging(global::System.String value);
        partial void OnEarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Frequency
        {
            get
            {
                return _Frequency;
            }
            set
            {
                OnFrequencyChanging(value);
                ReportPropertyChanging("Frequency");
                _Frequency = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Frequency");
                OnFrequencyChanged();
            }
        }
        private global::System.Int32 _Frequency;
        partial void OnFrequencyChanging(global::System.Int32 value);
        partial void OnFrequencyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Intensity
        {
            get
            {
                return _Intensity;
            }
            set
            {
                OnIntensityChanging(value);
                ReportPropertyChanging("Intensity");
                _Intensity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Intensity");
                OnIntensityChanged();
            }
        }
        private global::System.Int32 _Intensity;
        partial void OnIntensityChanging(global::System.Int32 value);
        partial void OnIntensityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reponse
        {
            get
            {
                return _reponse;
            }
            set
            {
                OnreponseChanging(value);
                ReportPropertyChanging("reponse");
                _reponse = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("reponse");
                OnreponseChanged();
            }
        }
        private global::System.String _reponse;
        partial void OnreponseChanging(global::System.String value);
        partial void OnreponseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 audiogram_Audiometer
        {
            get
            {
                return _audiogram_Audiometer;
            }
            set
            {
                Onaudiogram_AudiometerChanging(value);
                ReportPropertyChanging("audiogram_Audiometer");
                _audiogram_Audiometer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("audiogram_Audiometer");
                Onaudiogram_AudiometerChanged();
            }
        }
        private global::System.Int32 _audiogram_Audiometer;
        partial void Onaudiogram_AudiometerChanging(global::System.Int32 value);
        partial void Onaudiogram_AudiometerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Audiogram_Audiometer1", "Audiometer")]
        public Audiometer Audiometer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Audiometer>("ApplicationData.Audiogram_Audiometer1", "Audiometer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Audiometer>("ApplicationData.Audiogram_Audiometer1", "Audiometer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Audiometer> AudiometerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Audiometer>("ApplicationData.Audiogram_Audiometer1", "Audiometer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Audiometer>("ApplicationData.Audiogram_Audiometer1", "Audiometer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Audiometer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Audiometer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Audiometer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="audiometer_Pacient">Initial value of the audiometer_Pacient property.</param>
        public static Audiometer CreateAudiometer(global::System.Int32 id, global::System.Int32 audiometer_Pacient)
        {
            Audiometer audiometer = new Audiometer();
            audiometer.Id = id;
            audiometer.audiometer_Pacient = audiometer_Pacient;
            return audiometer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> takenon
        {
            get
            {
                return _takenon;
            }
            set
            {
                OntakenonChanging(value);
                ReportPropertyChanging("takenon");
                _takenon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("takenon");
                OntakenonChanged();
            }
        }
        private Nullable<global::System.DateTime> _takenon;
        partial void OntakenonChanging(Nullable<global::System.DateTime> value);
        partial void OntakenonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 audiometer_Pacient
        {
            get
            {
                return _audiometer_Pacient;
            }
            set
            {
                Onaudiometer_PacientChanging(value);
                ReportPropertyChanging("audiometer_Pacient");
                _audiometer_Pacient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("audiometer_Pacient");
                Onaudiometer_PacientChanged();
            }
        }
        private global::System.Int32 _audiometer_Pacient;
        partial void Onaudiometer_PacientChanging(global::System.Int32 value);
        partial void Onaudiometer_PacientChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Audiometer_Pacient1", "Pacient")]
        public Pacient Pacient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacient>("ApplicationData.Audiometer_Pacient1", "Pacient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacient>("ApplicationData.Audiometer_Pacient1", "Pacient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Pacient> PacientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Pacient>("ApplicationData.Audiometer_Pacient1", "Pacient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Pacient>("ApplicationData.Audiometer_Pacient1", "Pacient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Audiogram_Audiometer1", "Audiogram")]
        public EntityCollection<Audiogram> Audiogram
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Audiogram>("ApplicationData.Audiogram_Audiometer1", "Audiogram");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Audiogram>("ApplicationData.Audiogram_Audiometer1", "Audiogram", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ApplicationData", Name="Pacient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Pacient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Pacient object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="fname">Initial value of the fname property.</param>
        /// <param name="lname">Initial value of the lname property.</param>
        /// <param name="idno">Initial value of the idno property.</param>
        /// <param name="dob">Initial value of the dob property.</param>
        /// <param name="createdon">Initial value of the createdon property.</param>
        public static Pacient CreatePacient(global::System.Int32 id, global::System.String fname, global::System.String lname, global::System.String idno, global::System.DateTime dob, global::System.DateTime createdon)
        {
            Pacient pacient = new Pacient();
            pacient.Id = id;
            pacient.fname = fname;
            pacient.lname = lname;
            pacient.idno = idno;
            pacient.dob = dob;
            pacient.createdon = createdon;
            return pacient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fname
        {
            get
            {
                return _fname;
            }
            set
            {
                OnfnameChanging(value);
                ReportPropertyChanging("fname");
                _fname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fname");
                OnfnameChanged();
            }
        }
        private global::System.String _fname;
        partial void OnfnameChanging(global::System.String value);
        partial void OnfnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lname
        {
            get
            {
                return _lname;
            }
            set
            {
                OnlnameChanging(value);
                ReportPropertyChanging("lname");
                _lname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lname");
                OnlnameChanged();
            }
        }
        private global::System.String _lname;
        partial void OnlnameChanging(global::System.String value);
        partial void OnlnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idno
        {
            get
            {
                return _idno;
            }
            set
            {
                OnidnoChanging(value);
                ReportPropertyChanging("idno");
                _idno = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("idno");
                OnidnoChanged();
            }
        }
        private global::System.String _idno;
        partial void OnidnoChanging(global::System.String value);
        partial void OnidnoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dob
        {
            get
            {
                return _dob;
            }
            set
            {
                OndobChanging(value);
                ReportPropertyChanging("dob");
                _dob = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dob");
                OndobChanged();
            }
        }
        private global::System.DateTime _dob;
        partial void OndobChanging(global::System.DateTime value);
        partial void OndobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telf
        {
            get
            {
                return _telf;
            }
            set
            {
                OntelfChanging(value);
                ReportPropertyChanging("telf");
                _telf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telf");
                OntelfChanged();
            }
        }
        private global::System.String _telf;
        partial void OntelfChanging(global::System.String value);
        partial void OntelfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime createdon
        {
            get
            {
                return _createdon;
            }
            set
            {
                OncreatedonChanging(value);
                ReportPropertyChanging("createdon");
                _createdon = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdon");
                OncreatedonChanged();
            }
        }
        private global::System.DateTime _createdon;
        partial void OncreatedonChanging(global::System.DateTime value);
        partial void OncreatedonChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ApplicationData", "Audiometer_Pacient1", "Audiometer")]
        public EntityCollection<Audiometer> Audiometer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Audiometer>("ApplicationData.Audiometer_Pacient1", "Audiometer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Audiometer>("ApplicationData.Audiometer_Pacient1", "Audiometer", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
