//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace C__Users_isaias_izquierdo_Documents_audiometer_sdfData.Implementation
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext object using the connection string found in the 'C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext' section of the application configuration file.
        /// </summary>
        public C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext() : base("name=C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext", "C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext object.
        /// </summary>
        public C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext(string connectionString) : base(connectionString, "C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext object.
        /// </summary>
        public C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext(EntityConnection connection) : base(connection, "C__Users_isaias_izquierdo_Documents_audiometer_sdfDataObjectContext")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
